version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgis/postgis:15-3.4
    restart: always
    volumes:
      - postgres-15:/var/lib/postgresql/data
      #- /home/hogis/dump:/root/dump
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=vinka
      - POSTGRES_USER=vinka
      - POSTGRES_DB=vinka
      - SHELL=/bin/bash
  redis:
    container_name: redis
    image: redis:6
    restart: always
    ports: 
      - "6379:6379"
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.12-rc-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit-volume:/var/lib/rabbitmq
  metronome:
    container_name: metronome
    image: eu.gcr.io/vinka-224008/metronome:1.3.1
    restart: always
    links:
      - rabbit
    environment:
      - CL_RABBIT_URL=amqp://rabbit
volumes:
  rabbit-volume:
    external: true
  postgres-15:
    external: true

